services:
  - type: web
    name: lms-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com/api